### ISSUE TITLE
GPU not detected when running Python script via SSH/zrok inside the terminal

### ISSUE THREAD

**Issue by SyahrulApr86** [int11/Kaggle_remote_zrok#1]
When running a Python script (`train.py`) through the Kaggle remote environment (via SSH/zrok tunnel), PyTorch reports `No GPU available`, even though the same code in the Kaggle Notebook kernel detects GPUs normally.

**To Reproduce**

1. Start a Kaggle Notebook with **GPU T4×2** enabled.
2. Run the following in the Notebook cell:

   ```python
   import torch
   print(torch.cuda.is_available(), torch.__version__, torch.version.cuda)
   ```

   Output: `True 2.6.0+cu124 12.4` → GPU available.
3. Connect via SSH/zrok, enter the working directory, then run:

   ```bash
   python train.py
   ```

   Output:

   ```
   No GPU available
   ```

   Despite `/usr/local/bin/python` being the same interpreter.

**Expected behavior**
`torch.cuda.is_available()` should return **True** both in the Notebook kernel and when running the same Python interpreter via SSH.

**Comment by int11** [comment]
Thank you for pointing out this issue. I’ve also confirmed this issue.
It looks like the root cause is that CUDA environment variables are not properly set when using an SSH remote.

This should be addressed in commits f4ab388b71f5e5f2a87fe622b945aed4272ad257 and e4a2776759c974e2640c3fc6ea5a2b9f6423d889.

Could you please check and confirm?

**Comment by SyahrulApr86** [comment]
I’ve re-checked after the latest commits (`f4ab388`, `e4a2776`) and can confirm that the problem is now resolved.

Running the same script via SSH/zrok now correctly detects GPUs:


Thanks a lot for the quick fix and support! 🙌

<img width="378" height="154" alt="Image" src="https://github.com/user-attachments/assets/05e5a7f9-6fd9-4cf5-9a14-2aa924b3d17f" />
